language: node_js
node_js: lts/erbium
deploy:
  provider: pages
  local_dir: .
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  email: tituswormer@gmail.com
  name: Titus Wormer
  on:
    branch: blm
